### ISSUE TITLE
Invalid expiration

### ISSUE THREAD

**Issue by scottmcpherson** [RobertLowe/meteor-accounts-trello#1]
Hey @RobertLowe , 

I added your package and I'm trying to get it working with my app. 
I'm using accounts UI to include the button. When I click configure trello login, I add my key, secret, and app name. The other two option—scope and expiration—say that you can leave them blank. But it won't let me submit the form with filling something in. So for scope, I just put "app", and for Expiration I put 100000.

And I try to login and I get: "Invalid expiration".

I know this is an old package, but is there any chance you could please help me get it working?

**Comment by scottmcpherson** [comment]
Also, in the terminal I get the following errer:
`(oauth_server.js:78) Unable to parse state from OAuth query: ú)FæúY`

**Comment by RobertLowe** [comment]
This has been fixed with the new release. Cheers
